### PR TITLE
Support for pathPrefix when using S3 storage. Also fixed some references…

### PR DESCRIPTION
**Pull request by SeanHayes**
... to `super` with `this`.

### CODE REVIEW

**Comment by SeanHayes** [comment]
I've tested this manually and verified that it works.

**Comment by colinmeinke** [comment]
@SeanHayes thanks for the PR! Looks good to me.

Before I merge could you give an example of the use case for this (I assume it's for when you want to save to a specific directory of a bucket?).

Also, for my own interest, why is using `this.getTargetDir` better than `super.getTargetDir`? As far as I understand prototypal inheritance, they would both reference the parent object's `getTargetDir`?

**Comment by SeanHayes** [comment]
Yes, it's to save in a "subdirectory" on S3, so my blog content can be namespaced on an existing bucket with other content.

`this` refers to the current object; trying to access a method not defined on the current class will fallback to the parent, whereas `super` always refers to the parent. It's better to use `this` so that a class can be subclassed and have methods overridden (something I wasn't able to do because I believe the use of `super.getTargetDir()` was causing my subclass' `getTargetDir()` method to be skipped entirely in favor of the parents').

**Comment by colinmeinke** [comment]
Great, thanks @SeanHayes!

**Comment by colinmeinke** [comment]
Released https://github.com/colinmeinke/ghost-storage-adapter-s3/releases/tag/v1.2.0

**Comment by SeanHayes** [comment]
Thanks for getting this out so fast!

**Pull request merged**
